# Generated by Django 5.0.4 on 2024-05-02 05:19

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Niknaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('direct_by', models.CharField(max_length=40)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.category')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_count', models.IntegerField()),
                ('source', models.FileField(blank=True, null=True, upload_to='video/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.media')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('chatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.chatroom')),
                ('niknaimid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.niknaim')),
            ],
        ),
    ]
