# Generated by Django 5.0.4 on 2024-05-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='ComentName',
        ),
    ]
